# Generated by Django 2.1.5 on 2020-03-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20181028_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name', 'patronomic_name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='author',
            name='patronomic_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'На оформлении'), ('o', 'На руках'), ('a', 'Доступна'), ('r', 'Зарезервированна')], default='d', help_text='Book availability', max_length=1),
        ),
    ]
