# Generated by Django 2.1.5 on 2020-03-04 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20200303_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a borrower', primary_key=True, serialize=False),
        ),
    ]
